// destination: src/app/project/arcade/games/wordData.ts

export const WORDS_BY_LENGTH: Record<number, string[]> = {
  3: [
    "ace", "act", "age", "aid", "aim", "air", "ale", "ant", "arc", "are", "arm", "art", "ash", "ask", "ate",
    "bad", "bag", "bar", "bat", "bed", "bee", "bet", "bid", "big", "bit", "bow", "box", "boy", "bug", "bus",
    "cab", "can", "cap", "car", "cat", "cod", "con", "cop", "cot", "cow", "cut", "day", "den", "dig", "dog",
    "dot", "dry", "due", "ear", "eat", "end", "era", "fan", "far", "fat", "fig", "fin", "fit", "fog", "fun",
    "gap", "gas", "gel", "gem", "get", "got", "gum", "gun", "hat", "hit", "hot", "ice", "ink", "jam", "jar",
    "jet", "job", "joy", "key", "kid", "kit", "lap", "law", "lay", "led", "let", "lid", "lie", "lit", "log",
    "lot", "mad", "man", "map", "mat", "met", "mix", "net", "new", "nod", "nor", "not", "now", "oak", "oar",
    "odd", "oil", "old", "one", "ore", "our", "out", "pad", "pan", "pat", "pen", "pet", "pie", "pig", "pin",
    "pit", "ran", "rat", "raw", "red", "rid", "rig", "rim", "rip", "rod", "rot", "row", "rub", "rug", "run",
    "sad", "sat", "saw", "sea", "see", "set", "sin", "sit", "son", "sun", "tag", "tan", "tap", "tar", "tea",
    "ten", "tie", "tin", "toe", "ton", "top", "toy", "use", "van", "war", "was", "web", "wet", "win", "won",
    "yes", "yet"
  ],
  4: [
    "acre", "aged", "also", "ante", "area", "atom",
    "bait", "bake", "bale", "band", "bare", "base", "beam", "bear", "beat", "bend", "best", "bird", "bite",
    "blue", "boat", "bold", "bone", "boon", "bore", "born", "brag", "bred", "brew", "brim", "bulk", "bunk", "burn", "bust",
    "cafe", "cage", "came", "camp", "card", "care", "cart", "case", "cast", "chef", "chin", "clam", "claw", "clog",
    "code", "cold", "come", "cone", "cope", "cord", "core", "cove", "crew", "crop",
    "damp", "dare", "dark", "date", "deal", "deer", "demo", "dice", "dire", "dirt", "disk", "dock", "does", "done",
    "dove", "drag", "draw", "dual", "duel", "dune", "dunk", "dusk",
    "each", "earn", "ease", "east", "edge", "edit", "emit", "even", "ever",
    "face", "fact", "fade", "farm", "fast", "fate", "fear", "feed", "file", "fine", "fire", "firm", "fish", "fist",
    "five", "flat", "flow", "foam", "fold", "folk", "form", "fort", "free", "frog", "funk",
    "game", "gawk", "gear", "gene", "gift", "girl", "glob", "glow", "gnaw", "goal", "gold", "good",
    "gray", "grew", "grid", "grin", "grow", "gulf", "gulp", "gust",
    "hack", "hard", "harm", "hate", "hawk", "head", "hear", "heat", "held", "hero", "hide", "hire", "hold", "home",
    "honk", "hulk", "hunk", "husk",
    "idle", "iron", "itch",
    "jinx", "joke", "jolt", "jump", "junk",
    "kelp", "kind", "king", "kite", "knob", "knot",
    "lace", "land", "lane", "lark", "lash", "late", "lawn", "lead", "leaf", "lean", "left", "lend", "lens",
    "liar", "line", "lion", "load", "loan", "lock", "loft", "long", "lord", "lurk", "lush", "lynx",
    "made", "mail", "main", "make", "male", "mane", "mare", "mark", "meal", "mean", "meat", "melt",
    "milk", "mind", "mine", "mint", "mode", "more", "moth", "musk", "myth",
    "name", "near", "neat", "need", "nest", "note", "numb",
    "onyx", "open",
    "pace", "pack", "page", "paid", "pair", "pale", "pane", "part", "past", "path", "peak", "pear",
    "plan", "play", "plot", "ploy", "plum", "poem", "pond", "post", "puck",
    "quip",
    "race", "rage", "raid", "rain", "rake", "rank", "rash", "rate", "read", "real", "redo", "reed",
    "rein", "rent", "rest", "rice", "ride", "rile", "risk", "road", "rode", "role", "rope", "rose", "ruby", "rule",
    "rush", "rusk", "rust",
    "same", "sand", "save", "scan", "scar", "seal", "seam", "seat", "seed", "send", "sent",
    "shed", "shin", "ship", "shoe", "side", "sign", "silk", "site", "slab", "slap", "slid", "slug", "smug",
    "snap", "snob", "snug", "soap", "soil", "solo", "span", "spin", "star", "stem", "step", "stop",
    "stub", "stud", "sulk", "sunk", "swap",
    "take", "tale", "tame", "team", "tear", "tend", "term", "than", "tile", "time",
    "tone", "tore", "torn", "trap", "tree", "trip", "tuck", "turn", "tusk", "twig",
    "unit", "used", "user",
    "vase", "volt", "vote",
    "wake", "ward", "warm", "wave", "wear", "wide", "wilt", "wind", "wing", "wink", "wisp", "wolf", "word", "work",
    "yard", "year", "yawn", "yell", "yelp", "yolk",
    "zinc", "zest", "zoom"
  ],
  5: [
    "about", "above", "actor", "admit", "adopt", "adult", "after", "again", "agent", "agree", "ahead",
    "alarm", "album", "alien", "allow", "alone", "along", "alter", "amber", "angel", "anger", "apple",
    "arena", "argue", "arise", "aside", "audio", "avoid",
    "baker", "basic", "beach", "began", "begin", "black", "blade", "blame", "blank", "blast", "blend",
    "blunt", "block", "blood", "board", "boxer", "brain", "brand", "brave", "bread", "break", "brick",
    "bring", "broad", "broth", "brown", "build", "bunch", "burst",
    "cable", "carry", "cause", "chain", "chair", "chart", "chase", "cheap", "check", "chest", "chief",
    "child", "claim", "clamp", "class", "clean", "clear", "climb", "cloak", "clock", "cloud", "clown",
    "coach", "coast", "could", "count", "couch", "court", "cover", "craft", "crash", "crate", "cream",
    "crisp", "crime", "cross", "crowd", "crown", "curve",
    "daily", "dance", "death", "debug", "delay", "depth", "doubt", "draft", "drama", "dream", "dress",
    "drink", "drive", "dusty",
    "earth", "elite", "empty", "enemy", "enjoy", "enter", "entry", "equal", "error", "event", "every",
    "exact", "exist", "extra",
    "faith", "false", "fault", "field", "fight", "final", "first", "flame", "floor", "focus", "force",
    "frame", "fresh", "front", "fruit", "funky",
    "gaudy", "ghost", "giant", "glass", "globe", "grace", "grade", "grain", "grand", "grant", "graph",
    "grass", "great", "green", "groan", "group", "guard", "guess", "guest", "guide", "gusto",
    "handy", "happy", "haunt", "heart", "heavy", "hello", "hoist", "honor", "horse", "hotel", "house",
    "hound", "human", "hunch", "husky",
    "ideal", "image", "index", "inner", "input", "issue",
    "joint", "joust", "judge", "jumpy",
    "knack", "known",
    "label", "lanky", "large", "later", "laugh", "layer", "learn", "least", "leave", "level", "light",
    "limit", "livid", "local", "lodge", "lofty", "logic", "lucky",
    "macho", "magic", "major", "march", "marsh", "match", "maybe", "metal", "might", "minor", "model",
    "money", "month", "motor", "mount", "mouse", "mourn", "murky", "music",
    "nasty", "nifty", "night", "noise", "north", "notch", "novel",
    "occur", "ocean", "offer", "often", "optic", "orbit", "order", "other",
    "panel", "paper", "party", "peace", "perch", "phase", "phone", "piece", "pilot", "pitch", "pixel",
    "place", "plain", "plane", "plant", "plate", "pluck", "plush", "point", "pouch", "power", "prawn",
    "press", "prime", "print", "prior", "prize", "proof", "proud", "prune",
    "quack", "queen", "quick", "quiet", "quirk",
    "radio", "raise", "range", "rapid", "raspy", "ratio", "reach", "react", "ready", "reply", "right",
    "risky", "river", "robot", "rough", "round", "route", "rowdy", "royal", "rugby", "rusty",
    "sauna", "scale", "scene", "scope", "score", "scout", "sense", "serve", "setup", "shaft", "shady",
    "shade", "shape", "share", "sharp", "shawl", "sheet", "shelf", "shell", "shift", "shine", "shirt",
    "shock", "short", "shrug", "shown", "sight", "silky", "sixth", "skill", "skunk", "slang", "slick",
    "sleep", "slice", "sloth", "smart", "smash", "smear", "smirk", "snail",
    "solid", "solve", "sound", "south", "spade", "space", "speak", "speed", "spend", "spire", "split",
    "sport", "spunk", "stack", "stage", "stand", "stark", "start", "state", "steam", "steel", "stick",
    "still", "stomp", "stone", "store", "storm", "story", "strap", "stray", "stuck", "study", "stunt",
    "style", "swamp", "swipe", "swirl",
    "table", "tacky", "taunt", "teach", "tepid", "theme", "there", "thick", "thing", "think", "third",
    "thorn", "throw", "thump", "tight", "timer", "title", "today", "token", "topic", "total", "touch",
    "tower", "toxic", "trace", "track", "trade", "train", "trial", "trout", "truth", "tulip", "twang", "twirl",
    "under", "union", "unity", "urban", "usual",
    "valid", "value", "vault", "vegan", "video", "vigil", "vixen", "vocal", "vodka", "voice",
    "waltz", "waste", "watch", "water", "wheel", "where", "which", "while", "white", "whisk", "whole",
    "world", "worth", "would", "wrath", "write", "wrong",
    "yacht", "yield", "young", "zebra"
  ],
  6: [
    "anchor", "autumn",
    "banter", "basket", "bounty", "branch", "bridge", "button",
    "camera", "canyon", "castle", "charge", "circle", "cobalt", "coding", "combat", "copper", "crafty",
    "dagger", "dancer", "danger", "dragon",
    "engine",
    "falcon", "flower", "forest", "friend", "frozen", "fungus",
    "gallop", "garden", "garlic", "global", "goblin", "golden", "gravel", "guitar",
    "handle", "harbor", "hiking", "hornet", "hunter", "hustle",
    "impact", "island",
    "jigsaw", "jungle",
    "karate",
    "lancer", "lumber",
    "magnet", "marble", "market", "mascot", "memory", "mentor", "mobile", "monkey", "mortal", "motion",
    "nectar", "nimble",
    "pardon", "pastry", "patrol", "pencil", "pirate", "planet", "plasma", "pocket", "portal", "powder",
    "prince", "prison", "profit",
    "quartz",
    "radish", "random", "ranger", "raptor", "reform", "remote", "rescue", "return", "revolt", "ritual",
    "robust", "rocket",
    "safari", "salmon", "sanity", "screen", "sector", "shadow", "signal", "silver", "sketch", "sleuth",
    "socket", "spiral", "spring", "squash", "stable", "stream", "syntax", "system",
    "tactic", "talent", "target", "temple", "theory", "ticket", "timber", "tinker", "trance", "travel",
    "tribal", "trophy",
    "update",
    "vendor", "violet",
    "walnut", "warden", "warmth", "window", "winter", "wisdom",
    "yellow",
    "zenith", "zipper", "zombie"
  ],
  7: [
    "another",
    "balance", "builder",
    "cabinet", "camping", "captain", "capture", "catalog", "chapter", "climate", "comfort", "council",
    "courage", "crystal", "culture",
    "dolphin", "dungeon", "dynamic",
    "ecology",
    "fantasy", "farming", "fiction", "fighter", "foreign", "fortune", "freight",
    "gallant", "glimpse",
    "habitat", "harmony", "harvest", "horizon",
    "integer",
    "journey", "justice",
    "kingdom",
    "lantern", "library", "liberty",
    "machine", "mention", "million", "miracle", "mission", "monster",
    "natural", "network", "neutral",
    "pattern", "physics", "picture", "pioneer", "popular", "problem", "program",
    "quantum",
    "railway", "reality", "rebuild",
    "science", "shelter", "society", "soldier", "sparkle", "station", "student", "surface",
    "texture", "thunder", "tourism", "trading", "turbine",
    "uniform", "unusual",
    "version", "village", "vintage", "volcano",
    "walking", "warning", "writing",
    "zealous"
  ],
  8: [
    "absolute", "abstract", "academic",
    "airplane", "backyard", "balanced", "basement",
    "calendar", "campaign", "campfire", "champion", "chemical", "consider", "creative", "criminal", "customer",
    "database", "describe", "document",
    "engineer", "evaluate", "evidence",
    "festival", "firewall",
    "generate", "grateful",
    "hardware", "hospital",
    "identify", "industry", "innocent", "interior",
    "keyboard",
    "language",
    "material", "maximize", "medicine", "moderate", "mountain", "movement",
    "national", "negative", "notebook",
    "organize", "original",
    "password", "physical", "platform", "practice", "preserve", "priority", "property",
    "raindrop", "reaction", "reliable", "research", "resource", "response",
    "schedule", "security", "separate", "software", "solution", "specific", "strategy", "strength", "struggle",
    "terminal", "thousand", "together", "transfer", "treasure",
    "umbrella",
    "vacation", "valuable", "variable", "velocity",
    "wildlife", "wireless", "woodland", "workshop"
  ],
};

export const LETTER_CONNECT_SEEDS_BY_LENGTH: Record<number, string[]> = {
  4: [
    "PLAY", "WORD", "FISH", "JUMP", "BOLD", "WAVE", "CLAY", "SHIP", "MINT", "FROG",
    "BARK", "SNOW", "LAMP", "GLOW", "TILE", "DUST", "SILK", "HULK", "DUSK", "MOTH",
    "WINK", "ZINC", "VOLT", "YOLK", "LYNX",
  ],
  5: [
    "TRACE", "PLANT", "BRICK", "CLOUD", "SHARP", "MOUSE", "LIGHT", "BRAVE", "CHAIR", "SNAKE",
    "WORLD", "FRAME", "OCEAN", "MAGIC", "TOWER", "BLEND", "STOMP", "BUILT", "FUNKY", "OPTIC",
    "QUIRK", "VAULT", "WALTZ", "YACHT", "ZEBRA",
  ],
  6: [
    "PLANET", "CASTLE", "STREAM", "POCKET", "BRANCH", "FLOWER", "MARKET", "SILVER",
    "BUTTON", "DRAGON", "SPRING", "ANCHOR", "ROCKET", "BASKET", "BRIDGE", "CAMERA",
    "COMBAT", "COBALT", "RANDOM", "WINTER", "JUNGLE", "TRANCE", "HUNTER", "SIGNAL",
    "TROPHY", "WISDOM", "FROZEN", "ZOMBIE", "WALNUT", "ZENITH",
  ],
  7: [
    "BUILDER", "ANOTHER", "PICTURE", "JOURNEY", "CABINET", "KINGDOM", "LIBRARY", "MONSTER",
    "RAILWAY", "THUNDER", "WALKING", "FARMING", "HARMONY", "CAPTURE", "FREIGHT", "SOLDIER",
    "DOLPHIN", "CHAPTER", "CAPTAIN", "BALANCE", "MACHINE", "VINTAGE", "VOLCANO", "CRYSTAL",
  ],
  8: [
    "ENGINEER", "NOTEBOOK", "TREASURE", "MOUNTAIN", "BACKYARD", "CAMPFIRE", "PASSWORD", "KEYBOARD",
    "AIRPLANE", "BASEMENT", "HARDWARE", "SOFTWARE", "WORKSHOP", "FIREWALL", "RAINDROP",
    "CHAMPION", "ABSOLUTE", "CALENDAR", "TERMINAL", "CHEMICAL", "CREATIVE", "STRENGTH",
  ],
};

export function getWordsByLength(length: number) {
  return WORDS_BY_LENGTH[length] ?? [];
}

export function getAllArcadeWords() {
  return Object.values(WORDS_BY_LENGTH).flat();
}
